### ISSUE TITLE
增加多渠道集成示例

### ISSUE THREAD

**Issue by simpleton** [TinkerPatch/tinkerpatch-sample#2]

**Comment by TonyTangAndroid** [comment]
正要问这个问题，addIgnoreAppChannel，这个Channel 是 源自于哪里？ 比如说，我使用友盟的SDK，那么友盟指定Channel的方式是在 XML 文件里 添加 UMEGN_CHANNEL 的meta_data. 我默认TinkerPath肯定有自己的规范来要求我们制定 对应的Channel 数据源吧。

**Comment by simpleton** [comment]
新版本1.1.0 已经支持了，可以参照sample里的例子，后续我会更新一个更详细的例子。

**Comment by TonyTangAndroid** [comment]
`//设置当前渠道号,对于某些渠道我们可能会想屏蔽补丁功能
            //设置渠道后,我们就可以使用后台的条件控制渠道更新
            .setAppChannel("default")
            //屏蔽部分渠道的补丁功能
            .addIgnoreAppChannel("googleplay")
            //设置tinkerpatch平台的条件下发参数
            .setPatchCondition("test", "1")
`

`setAppChannel` 仅仅是 设置当前Apk的渠道号，对吧？

如果我想忽略googlePlay的话，
应该这样子做: 

`            .setAppChannel("googleplay")
            //屏蔽部分渠道的补丁功能
            .addIgnoreAppChannel("googleplay")`


请问我的理解正确不？

**Comment by simpleton** [comment]
是的:D

**Comment by TonyTangAndroid** [comment]
谢谢

**Comment by TonyTangAndroid** [comment]
不好意思，我还有另外一个问题，那就是如果我有多个渠道的话，我是需要为每一个渠道打包对应的Patch吗？ 我感觉，如果我不这样子做的话，新的patch对应的渠道会覆盖Base的渠道。

**Comment by simpleton** [comment]
这个需要看你每个渠道包的代码是否完全一样，如果代码都相同，可以只打一个patch。如果基础包代码不同，就得打不同的patch包

**Comment by simpleton** [comment]
另外需要看你渠道包标识的方法，插入zip包结构的方法是tinker官方推荐的

**Comment by TonyTangAndroid** [comment]
代码是相同的。期待有类似的Demo
