### ISSUE TITLE
Tinker.UrlConnectionFetcher: response code 404 msg: Not Found

### ISSUE THREAD

**Issue by jacpy** [TinkerPatch/tinkerpatch-sample#3]
你好，我这边用demo测试发现请求是404，请问怎么破？
请求的链接地址是：http://q.tinkerpatch.com/c/3783d2119a442544?d=0f83144b-cfce-4b9c-bf0c-569ba07a3f87&v=1484120270913
错误提示信息：
D/DeviceConnectionService: client connected with version: 6577000
D/DeviceConnectionService: client connected with version: 6577000
tinker.sample.android W/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/c/3783d2119a442544?d=0f83144b-cfce-4b9c-bf0c-569ba07a3f87&v=1484120270913, method:GET, body:null
tinker.sample.android D/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found

**Comment by simpleton** [comment]
可以检查下你是否在后台打开了开发预览 。

**Comment by jacpy** [comment]
开发预览已经打开了，切换到使用全量下发就OK了，返回200。但报如下错误：
java.security.SignatureException: Signature was not verified
 at org.apache.harmony.security.provider.cert.X509CertImpl.verify(X509CertImpl.java:378)
 at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.check(SourceFile:158)
 at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(SourceFile:133)
 at com.tinkerpatch.sdk.server.callback.TinkerPatchRequestCallback.onPatchUpgrade(SourceFile:196)
 at com.tinkerpatch.sdk.server.a.a$1$1.a(SourceFile:1138)
 at com.tinkerpatch.sdk.server.a.a$3.a(SourceFile:1248)
 at com.tinkerpatch.sdk.server.c.a$1.a(SourceFile:1060)
 at com.tinkerpatch.sdk.server.c.a$a.run(SourceFile:132)

然后我又把后台的补丁报删除，重新再创建一遍，使用开发预览，再新请求发现OK了，返回200，但是请求config还是404。

**Comment by jacpy** [comment]
后台我没有动，我现在又重复试了几次，点击REQUEST PATH按钮，发现请求OK，但是会报上面的java.security.SignatureException: Signature was not verified错误。一会儿之前试的还没有报这个错误，很无语。

**Comment by simpleton** [comment]
这块可能我文档没有交代清楚，我这里总结下，稍后更新文档。

后台的开发预览 只是针对补丁包的，只能安装了DebugTools并打开开关的同学拉去使用。
从你的log的url可以看出来是这个是全量的url，开发预览得url path中包含/dev的路径。

在线参数用于调整补丁下发的用户群，这里对开发预览是没有什么意义的。（这里log中也不应出现类似404的错误，我会立即做修复）。

你这里提出的SignatureException 是tinker本身校验补丁包抛出的错误，请保证patch包是基于手机上安装的apk生成的。

**Comment by jacpy** [comment]
DebugTools已经安装，并且已经打开了开关；后台也设置开发预览，但没有发现请求中包含有/dev路径。

将测试的Demo新旧两个版本都使用签名打包，再生成补丁包，手机上安装旧版本的Demo。然后在后台设置不管是使用开发预览还是全量下发，DebugTools的开关打开、关闭，都存上面的SignatureException错误。

**Comment by simpleton** [comment]
SignatureException是tinker校验签名的错误，你需要保证上传的patch包和你安装的base包是匹配的。

PS: DebugTools安装后，需要重启你的app进程。

2017-01-11 17:14 GMT+08:00 jacpy <notifications@github.com>:

**Comment by jacpy** [comment]
每次我都是清除应用数据重新再来了，如果不清除数据，就不会有SignatureException这个错误。

还是没搞定，没看到效果，我只能先放弃。谢谢回复。

**Comment by simpleton** [comment]
@jacpy 如果不是开发预览，默认3小时才会拉去一次。。。

SignatureException是校验你baseApk和patch包签名不匹配而造成的。
