### ISSUE TITLE
运行assembleRelease出现问题	

### ISSUE THREAD

**Issue by heming0512** [TinkerPatch/tinkerpatch-sample#4]
运行assembleRelease，运行停止在:app:recordFilesBeforeBundleCommandZmlearnRelease	12ms	
这一栏，不知道是资源问题还是什么问题导致的，现将Gradle Console控制台上信息复制如下，望大神有空帮忙看一下：
----------------------tinker build warning ------------------------------------
tinker auto operation: 
excluding annotation processor and source template from app packaging. Enable dx jumboMode to reduce package size.
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is booting.

tinker will change your build configs:
we will add TINKER_ID=2.1.0 in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and we will help you to put it in the MultiDexKeepProguardFile.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk?
.........
tinker add tinker_id_2.1.0 to your AndroidManifest.xml /Users/chenheming/Documents/source/zm-course-android-mobile/android/app/build/intermediates/manifests/full/zmlearn/debug/AndroidManifest.xml
tinker add com.zmlearn.course.am.application.ZMLearnCourseAmApplication to dex loader pattern
tinker add com.tencent.tinker.loader.* to dex loader pattern
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml

:app:tinkerProcessZmlearnDebugResourceId
apply resource mapping file /Users/chenheming/Documents/source/zm-course-android-mobile/android/app/build/bakApk/app-1.0.0-0213-18-01-54/release/app-release-R.txt is illegal, just ignore
.....
然后BUILD SUCCESSFUL。
其它地方也没有相应的堆栈信息抛出。

**Comment by simpleton** [comment]
@heming0512 请先检查这个文件是否存在。
不过assembleRelease的话已经不使用上次编译的R.txt问题也不，这里这个warning可以忽略，keep R.txt是为了让资源的补丁包尽量的小。
